extends Node

# Nations that have qualified for at least one UEFA Euro or FIFA World Cup (2004–2024)
# Colors are approximations using Godot named Color constants
const NATIONS: Dictionary = {
	# Europe
	"Germany":          { "primary": Color.WHITE,      "secondary": Color.BLACK },
	"France":           { "primary": Color.BLUE,       "secondary": Color.WHITE },
	"Spain":            { "primary": Color.RED,        "secondary": Color.GOLD },
	"Italy":            { "primary": Color.DARK_BLUE,  "secondary": Color.WHITE },
	"England":          { "primary": Color.WHITE,      "secondary": Color.RED },
	"Netherlands":      { "primary": Color.ORANGE,     "secondary": Color.WHITE },
	"Portugal":         { "primary": Color.RED,        "secondary": Color.GREEN },
	"Belgium":          { "primary": Color.RED,        "secondary": Color.BLACK },
	"Croatia":          { "primary": Color.RED,        "secondary": Color.WHITE },
	"Poland":           { "primary": Color.WHITE,      "secondary": Color.RED },
	"Denmark":          { "primary": Color.RED,        "secondary": Color.WHITE },
	"Sweden":           { "primary": Color.YELLOW,     "secondary": Color.BLUE },
	"Switzerland":      { "primary": Color.RED,        "secondary": Color.WHITE },
	"Czech Republic":   { "primary": Color.RED,        "secondary": Color.WHITE },
	"Turkey":           { "primary": Color.RED,        "secondary": Color.WHITE },
	"Greece":           { "primary": Color.WHITE,      "secondary": Color.BLUE },
	"Ukraine":          { "primary": Color.YELLOW,     "secondary": Color.BLUE },
	"Russia":           { "primary": Color.RED,        "secondary": Color.WHITE },
	"Serbia":           { "primary": Color.RED,        "secondary": Color.BLUE },
	"Hungary":          { "primary": Color.RED,        "secondary": Color.WHITE },
	"Romania":          { "primary": Color.YELLOW,     "secondary": Color.BLUE },
	"Slovakia":         { "primary": Color.BLUE,       "secondary": Color.WHITE },
	"Slovenia":         { "primary": Color.WHITE,      "secondary": Color.BLUE },
	"Austria":          { "primary": Color.RED,        "secondary": Color.WHITE },
	"Bulgaria":         { "primary": Color.WHITE,      "secondary": Color.GREEN },
	"Iceland":          { "primary": Color.BLUE,       "secondary": Color.WHITE },
	"Wales":            { "primary": Color.RED,        "secondary": Color.WHITE },
	"Scotland":         { "primary": Color.DARK_BLUE,  "secondary": Color.WHITE },
	"Northern Ireland": { "primary": Color.GREEN,      "secondary": Color.WHITE },
	"Ireland":          { "primary": Color.GREEN,      "secondary": Color.WHITE },
	"Albania":          { "primary": Color.RED,        "secondary": Color.BLACK },
	"Bosnia":           { "primary": Color.BLUE,       "secondary": Color.YELLOW },
	"Montenegro":       { "primary": Color.RED,        "secondary": Color.GOLD },
	"North Macedonia":  { "primary": Color.RED,        "secondary": Color.YELLOW },
	"Finland":          { "primary": Color.WHITE,      "secondary": Color.BLUE },
	"Georgia":          { "primary": Color.WHITE,      "secondary": Color.RED },
	"Armenia":          { "primary": Color.RED,        "secondary": Color.BLUE },
	# South America
	"Brazil":           { "primary": Color.YELLOW,     "secondary": Color.GREEN },
	"Argentina":        { "primary": Color.CYAN,       "secondary": Color.WHITE },
	"Uruguay":          { "primary": Color.CYAN,       "secondary": Color.WHITE },
	"Colombia":         { "primary": Color.YELLOW,     "secondary": Color.BLUE },
	"Chile":            { "primary": Color.RED,        "secondary": Color.WHITE },
	"Ecuador":          { "primary": Color.YELLOW,     "secondary": Color.BLUE },
	"Peru":             { "primary": Color.WHITE,      "secondary": Color.RED },
	"Paraguay":         { "primary": Color.RED,        "secondary": Color.WHITE },
	"Bolivia":          { "primary": Color.GREEN,      "secondary": Color.RED },
	# North/Central America
	"Mexico":           { "primary": Color.GREEN,      "secondary": Color.RED },
	"USA":              { "primary": Color.WHITE,      "secondary": Color.BLUE },
	"Canada":           { "primary": Color.RED,        "secondary": Color.WHITE },
	"Costa Rica":       { "primary": Color.RED,        "secondary": Color.BLUE },
	"Honduras":         { "primary": Color.BLUE,       "secondary": Color.WHITE },
	"Panama":           { "primary": Color.RED,        "secondary": Color.WHITE },
	"El Salvador":      { "primary": Color.BLUE,       "secondary": Color.WHITE },
	"Trinidad & Tobago":{ "primary": Color.RED,        "secondary": Color.BLACK },
	"Jamaica":          { "primary": Color.YELLOW,     "secondary": Color.BLACK },
	"Haiti":            { "primary": Color.BLUE,       "secondary": Color.RED },
	# Asia
	"Japan":            { "primary": Color.DARK_BLUE,  "secondary": Color.WHITE },
	"South Korea":      { "primary": Color.RED,        "secondary": Color.WHITE },
	"Iran":             { "primary": Color.WHITE,      "secondary": Color.GREEN },
	"Saudi Arabia":     { "primary": Color.GREEN,      "secondary": Color.WHITE },
	"Australia":        { "primary": Color.GOLD,       "secondary": Color.GREEN },
	"Qatar":            { "primary": Color.PURPLE,     "secondary": Color.WHITE },
	"Iraq":             { "primary": Color.GREEN,      "secondary": Color.WHITE },
	"Jordan":           { "primary": Color.WHITE,      "secondary": Color.RED },
	# Africa
	"Nigeria":          { "primary": Color.GREEN,      "secondary": Color.WHITE },
	"Senegal":          { "primary": Color.WHITE,      "secondary": Color.GREEN },
	"Morocco":          { "primary": Color.RED,        "secondary": Color.GREEN },
	"Ghana":            { "primary": Color.WHITE,      "secondary": Color.BLACK },
	"Cameroon":         { "primary": Color.GREEN,      "secondary": Color.RED },
	"Ivory Coast":      { "primary": Color.ORANGE,     "secondary": Color.WHITE },
	"Algeria":          { "primary": Color.WHITE,      "secondary": Color.GREEN },
	"Tunisia":          { "primary": Color.RED,        "secondary": Color.WHITE },
	"Egypt":            { "primary": Color.RED,        "secondary": Color.WHITE },
	"South Africa":     { "primary": Color.GOLD,       "secondary": Color.GREEN },
	"Angola":           { "primary": Color.RED,        "secondary": Color.BLACK },
	"Mali":             { "primary": Color.GREEN,      "secondary": Color.YELLOW },
	"Togo":             { "primary": Color.GREEN,      "secondary": Color.YELLOW },
	"New Zealand":      { "primary": Color.WHITE,      "secondary": Color.BLACK },
}
